version: '3'
services:
  db:
    image: postgres

  redis:
    image: 'redis'
    ports:
      - '6379:6379'

  testing_app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/testing_app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis